### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'this.htmlText.removeAttributeRange')

### ISSUE THREAD

**Issue by danielgek** [Akylas/nativescript-label#1]
The function needs to be arrow function otherwise `this.htmlText` is null 

https://github.com/Akylas/nativescript-label/blob/0ac09b4120d90951d918fa9026ec41df651b10fd/src/label.ios.ts#L148

**Comment by farfromrefug** [comment]
@danielgek thanks! fixed in 1.0.5

**Comment by danielgek** [comment]
@farfromrefug wow that was fast, in meanwhile got another problem will open another issue
