### ISSUE TITLE
vertical-text-alignment

### ISSUE THREAD

**Issue by shilik** [Akylas/nativescript-label#3]
Hi @farfromrefug 

I would like to know if the property of vertical-text-alignment can be used for text to align vertically? Some languages like Japanese or Chinese can be formatted vertically than from left to right. 
If it would be greatly appreciated if the vertical-text-algnment that can do the above task.

**Comment by farfromrefug** [comment]
@shilik no it is not for that.
You need to create your own plugin.
Maybe based on this https://github.com/lybeat/PlumbTextView
