### ISSUE TITLE
Undefined is not an object (this.style.fontInternal.fontFamily)

### ISSUE THREAD

**Issue by seergiue** [Akylas/nativescript-label#6]
### Which platform(s) does your issue occur on?

- iPhone Emulator running iOS 13.6

### Please, provide the following version numbers that your issue occurs with:

- CLI: (run `tns --version` to fetch it)
**6.8.0**
- Cross-platform modules: (check the 'version' attribute in the
`node_modules/@nativescript/core/package.json` file in your project)
**6.5.13**
- Runtime(s): (look for the `"tns-android"` and `"tns-ios"` properties in the `package.json` file of your project)
**tns-android: 6.5.3
tns-ios: 6.5.2**
- Plugin(s): (look for the version numbers in the `package.json` file of your
project and paste your dependencies and devDependencies here)
**1.0.41**

### Please, tell us how to recreate the issue in as much detail as possible. 
I'm using nativescript-vue and I've been using this plugin for some months now without any issue. Today I decided to update tns (I was on 6.5.X) and both platforms and when I display HtmlLabel with some HTML (like a paragraph to test an easy HTML code) it breaks saying the following: _TypeError: undefined is not an object (evaluating 'this.style.fontInternal.fontFamily')_

**Comment by farfromrefug** [comment]
So not sure about the latest version I published there.
The thing is now the plugin lives at @nativescript-community/ui-label.
So.if you are at latest and it still fails, either:
* try the new one at @nativescript-community but it is for N 7.0 so might not work
* rollback to the version you were using before until N 7 is out. Sorry for the trouble

**Comment by seergiue** [comment]
Thanks for the info @farfromrefug but unfortunately (and as expected) the new @nativescript-community/ui-label is not working.

I finally solved it by rolling back to v1.0.28 (working version).
